import {
  AiFillDashboard,
  AiOutlineShoppingCart,
  AiOutlinePlus,
  AiOutlineUser,
} from "react-icons/ai";
import { BiCategory, BiLoaderCircle } from "react-icons/bi";
import { FiUsers } from "react-icons/fi";
import { CiChat1 } from "react-icons/ci";
import { BsChat, BsCartDashFill } from "react-icons/bs";
import { RiProductHuntLine } from "react-icons/ri";
import { MdProductionQuantityLimits } from "react-icons/md";
import { FaShippingFast, FaUserAstronaut } from "react-icons/fa";
import { MdOutlineLocalShipping } from "react-icons/md";
import { HiUsers } from "react-icons/hi2";
export const allNav = [
  {
    id: 1,
    title: "Dashboard",
    icon: <AiFillDashboard />,
    role: "admin",
    path: "/admin/dashboard",
  },
  {
    id: 5,
    title: "Thêm Sản Phẩm",
    icon: <AiOutlinePlus />,
    role: "admin",
    path: "/admin/dashboard/add-product",
  },
  {
    id: 10,
    title: "Tất Cả Sản Phẩm",
    icon: <RiProductHuntLine />,
    role: "admin",
    path: "/admin/dashboard/products",
  },
  {
    id: 2,
    title: "Đặt Hàng",
    icon: <AiOutlineShoppingCart />,
    role: "admin",
    path: "/admin/dashboard/orders",
  },
  {
    id: 3,
    title: "Danh Mục, Thương Hiệu",
    icon: <BiCategory />,
    role: "admin",
    path: "/admin/dashboard/category",
  },
  {
    id: 14,
    title: "Thêm Mã Khuyến Mãi",
    icon: <RiProductHuntLine />,
    role: "admin",
    path: "/admin/dashboard/discount-products",
  },
  {
    id: 38,
    title: "Nhà Cung Cấp",
    icon: <MdOutlineLocalShipping />,
    role: "admin",
    path: "/admin/dashboard/nhacungcap",
  },
  {
    id: 15,
    title: "Phiếu Nhập Hàng",
    icon: <MdProductionQuantityLimits />,
    role: "admin",
    path: "/admin/dashboard/log-product",
  },
  {
    id: 30,
    title: "Shipper Nhận Đơn",
    icon: <FaShippingFast />,
    role: "admin",
    path: "/admin/dashboard/shipper-comfirm",
  },
  {
    id: 36,
    title: "Đánh Giá Đơn Hàng",
    icon: <BsCartDashFill />,
    role: "admin",
    path: "/admin/dashboard/all-review-order",
  },
  {
    id: 37,
    title: "Đánh Giá Sản Phẩm",
    icon: <BsCartDashFill />,
    role: "admin",
    path: "/admin/dashboard/all-review-product",
  },
  {
    id: 31,
    title: "Người Mua Trả Hàng",
    icon: <BsCartDashFill />,
    role: "admin",
    path: "/admin/dashboard/request",
  },
  {
    id: 4,
    title: "Nhân Viên",
    icon: <FiUsers />,
    role: "admin",
    path: "/admin/dashboard/sellers",
  },

  // {
  //   id: 6,
  //   title: "Kích Hoạt Nhân Viên",
  //   icon: <FiUsers />,
  //   role: "admin",
  //   path: "/admin/dashboard/deactive-sellers",
  // },
  // {
  //   id: 7,
  //   title: "Yêu Cầu Nhân Viên",
  //   icon: <BiLoaderCircle />,
  //   role: "admin",
  //   path: "/admin/dashboard/sellers-request",
  // },
  {
    id: 8,
    title: "Chat Với Nhân Viên",
    icon: <CiChat1 />,
    role: "admin",
    path: "/admin/dashboard/chat-sellers",
  },
  {
    id: 9,
    title: "Tạo Tài Khoản Nhân Viên",
    icon: <AiOutlineUser />,
    role: "admin",
    path: "/admin/dashboard/register-nvadmin",
  },
  {
    id: 10,
    title: "Tạo Tài Khoản Shipper",
    icon: <FaUserAstronaut />,
    role: "admin",
    path: "/admin/dashboard/register-shipper",
  },
  {
    id: 2,
    title: "Danh Sách Shipper",
    icon: <HiUsers />,
    role: "admin",
    path: "/admin/dashboard/ds-shipper",
  },
  {
    id: 35,
    title: "Danh Sách TK Khách",
    icon: <HiUsers />,
    role: "admin",
    path: "/admin/dashboard/ds-customers",
  },
  // {
  //   id: 11,
  //   title: "Dashboard",
  //   icon: <AiFillDashboard />,
  //   role: "nv_quanly",
  //   path: "/seller/dashboard",
  // },
  {
    id: 12,
    title: "Thêm Sản Phẩm",
    icon: <AiOutlinePlus />,
    role: "nv_sanpham",
    path: "/seller/dashboard/add-product",
  },
  {
    id: 13,
    title: "Tất Cả Sản Phẩm",
    icon: <RiProductHuntLine />,
    role: "nv_sanpham",
    path: "/seller/dashboard/products",
  },
  {
    id: 14,
    title: "Thêm Mã Khuyến Mãi",
    icon: <RiProductHuntLine />,
    role: "nv_sanpham",
    path: "/seller/dashboard/discount-products",
  },
  {
    id: 15,
    title: "Phiếu Nhập Hàng",
    icon: <MdProductionQuantityLimits />,
    role: "nv_nhapkho",
    path: "/seller/dashboard/log-product",
  },
  {
    id: 16,
    title: "Đơn Hàng",
    icon: <AiOutlineShoppingCart />,
    role: "nv_donhang",
    path: "/seller/dashboard/orders",
  },
  {
    id: 30,
    title: "Shipper Nhận Đơn",
    icon: <FaShippingFast />,
    role: "nv_donhang",
    path: "/seller/dashboard/shipper-comfirm",
  },
  // {
  //   id: 17,
  //   title: "Chuyển Tiền",
  //   icon: <BsCurrencyDollar />,
  //   role: "seller",
  //   path: "/seller/dashboard/payments",
  // },
  {
    id: 31,
    title: "Người Mua Trả Hàng",
    icon: <BsCartDashFill />,
    role: "nv_donhang",
    path: "/seller/dashboard/request",
  },
  {
    id: 18,
    title: "Chat Với Người Mua",
    icon: <BsChat />,
    role: "nv_quanly",
    path: "/seller/dashboard/chat-customer",
  },
  {
    id: 19,
    title: "Chat Với Quản Lý",
    icon: <CiChat1 />,
    role: "nv_quanly",
    path: "/seller/dashboard/chat-support",
  },
  {
    id: 19,
    title: "Chat Với Quản Lý",
    icon: <CiChat1 />,
    role: "nv_nhapkho",
    path: "/seller/dashboard/chat-support",
  },
  {
    id: 19,
    title: "Chat Với Quản Lý",
    icon: <CiChat1 />,
    role: "nv_sanpham",
    path: "/seller/dashboard/chat-support",
  },
  {
    id: 19,
    title: "Chat Với Quản Lý",
    icon: <CiChat1 />,
    role: "nv_donhang",
    path: "/seller/dashboard/chat-support",
  },
  {
    id: 36,
    title: "Đánh Giá Đơn Hàng",
    icon: <BsCartDashFill />,
    role: "nv_donhang",
    path: "/admin/dashboard/all-review-order",
  },
  {
    id: 20,
    title: "Hồ Sơ",
    icon: <FiUsers />,
    role: "nv_donhang",
    path: "/seller/dashboard/profile",
  },
  {
    id: 20,
    title: "Hồ Sơ",
    icon: <FiUsers />,
    role: "nv_sanpham",
    path: "/seller/dashboard/profile",
  },
  {
    id: 20,
    title: "Hồ Sơ",
    icon: <FiUsers />,
    role: "nv_nhapkho",
    path: "/seller/dashboard/profile",
  },
  {
    id: 20,
    title: "Hồ Sơ",
    icon: <FiUsers />,
    role: "nv_quanly",
    path: "/seller/dashboard/profile",
  },
  {
    id: 21,
    title: "Dashboard",
    icon: <AiFillDashboard />,
    role: "nhanvien_admin",
    path: "/nhanvien-admin/dashboard",
  },
  {
    id: 23,
    title: "Thể Loại",
    icon: <BiCategory />,
    role: "nhanvien_admin",
    path: "/nhanvien-admin/dashboard/category",
  },
  {
    id: 24,
    title: "Người Bán",
    icon: <FiUsers />,
    role: "nhanvien_admin",
    path: "/nhanvien-admin/dashboard/sellers",
  },
  {
    id: 26,
    title: "Người Bán Chưa Kích Hoạt",
    icon: <FiUsers />,
    role: "nhanvien_admin",
    path: "/nhanvien-admin/dashboard/deactive-sellers",
  },

  {
    id: 27,
    title: "Yêu Cầu Người Bán",
    icon: <BiLoaderCircle />,
    role: "nhanvien_admin",
    path: "/nhanvien-admin/dashboard/sellers-request",
  },

  {
    id: 29,
    title: "Đơn Hàng",
    icon: <AiFillDashboard />,
    role: "shipper",
    path: "/shipper/dashboard",
  },
];
